name: widget_perf_real_time
description: A new Flutter package project.
version: 0.0.1
homepage: https://pub.dev/packages/widget_perf_real_time
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_performance: ^0.9.2+1
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  flutter_coverage_badge:
    git:
      url: https://github.com/foresightmobile/flutter_coverage_badge
      ref: 4d6371f1bd46fee1bd28a697e303412839e53548
