# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Flutter SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/subosito/flutter-action/blob/main/README.md
      - name: Flutter action
      # You may pin to the exact commit or the version.
      # uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        uses: subosito/flutter-action@v2
        with:
          # The Flutter version to make available on the path
          flutter-version: stable # optional, default is any
          # The Flutter build release channel
          channel: 'stable' # optional, default is stable
          # Cache the Flutter SDK
          # cache: # optional
          cache: true
          # Identifier for the Flutter SDK cache
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          # Flutter SDK cache path
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
          # The architecture of Flutter SDK executable (x64 or arm64)
          architecture: x64 # optional, x64 or arm64. default is ${{ runner.arch }}

      - name: Flutter Version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: flutter test
